name: boardytale_client
description: boardytale_client
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  angular: any
  utils:
    path: '../utils'
  stagexl: any
  boardytale_commons:
    path: '../boardytale_commons'
  tales_compiler:
    path: '../tales_compiler'
  angular_components: any
  browser: any
  angular_router: any
dev_dependencies:
  pub_serve_rewrites: any

transformers:
- angular:
    entry_points:
      - web/main.dart
