name: generator
version: 0.0.1
author: mlcoch.zdenek@gmail.com
description: Generates utilities to aid in serializing to/from JSON.
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  analyzer: '>=0.32.2 <0.34.0'
  source_gen: ^0.9.0
