name: boardytale_commons
description: Multiplayre webgame on hexagonal fields common library

environment:
  sdk: 2.0.0

dependencies:
  utils:
    path: '../utils'

dev_dependencies:
  build_runner: any
  test: any
  generator:
    path: '../generator'
  #json_serializable:
    #path: '../json_serializable/json_serializable'


