name: boardytale_commons
description: Multiplayre webgame on hexagonal fields common library

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  utils:
    path: '../libs/utils'

dev_dependencies:
  build_runner: any
  test: any
  json_serializable: any
  typescript_generator:
    path: ../typescript_generator/


