analyzer:
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  exclude:
    - from_prev_versions/**
    - class_generator/**
    - tales_compiler/**

linter:
  rules:
    - avoid_empty_else
    - cancel_subscriptions
    - close_sinks