name: ai_server
description: Hero service for Boardytale game
version: 0.0.1
author: Zdeněk Mlčoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  uuid: any
  shelf: any
  shelf_web_socket: any
  core:
    path: ../core
  io_utils:
    path: ../libs/io_utils
  rxdart: ^0.20.0
  stagexl: ^1.4.0+2
