name: editor_client
description: Map editor for Boardytale project
version: 1.0.0
homepage: https://www.boardytale.com
author: Zdeněk Mlčoch<mlcoch.zdenek@gmail.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  js: any
  ng2_g_signin:
    git: https://github.com/Boardytale/ng2_g_signin
  shared:
    path: ../shared

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  test: ^1.5.1
  sass: ^1.15.2
  io_utils:
    path: ../libs/io_utils
