name: io_utils
description: Common file tasks

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  path: any
  args: any
  shared:
    path: '../shared'
  utils:
    path: '../libs/utils'
  console: any


