name: typescript_generator
description: Generate typescritp envelope for potentially json serializable dart class
version: 1.0.2
author: Zdeněk Mlčoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  build: '>=0.12.0 <2.0.0'
  source_gen: ^0.9.0
  generate_typescript:
    path: ../libs/generate_typescript

  
dev_dependencies:
  build_test: ^0.10.0
  build_runner: '>=0.9.0 <0.11.0'
  test: ^1.0.0