name: boardytale_server
description: Server side for Boardytale game
version: 0.0.1
author: Zdeněk Mlčoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  tales_compiler:
    path: '../tales_compiler'
  boardytale_commons:
    path: '../boardytale_commons'
  shelf: any
  shelf_auth: any
  shelf_route: any
  shelf_cors: any
  shelf_exception_response: any
  shelf_web_socket: any