name: boardytale_server
description: Server side for Boardytale game
version: 0.0.1
author: Zdeněk Mlčoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: 2.0.0

dependencies:
  aqueduct: ^3.0.0
  tales_compiler:
    path: '../tales_compiler'
  boardytale_commons:
    path: '../boardytale_commons'