name: boardytale_server
description: Server side for Boardytale game
version: 0.0.1
author: Zdeněk Mlčoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  aqueduct: any
  tales_compiler:
    path: '../tales_compiler'