name: tales_compiler
description: Utility for validate and compile assets to json files

environment:
  sdk: 2.0.0

dependencies:
  io_utils:
    path: '../io_utils'
  boardytale_commons:
    path: '../boardytale_commons'
  image: any
dev_dependencies:
  test: "^0.12.0"

