name: tales_compiler
description: Utility for validate and compile assets to json files
dependencies:
  io_utils:
    path: '../io_utils'
  boardytale_commons:
    path: '../common'
  image: any
dev_dependencies:
  test: "^0.12.0"

