name: game_server
description: Server side for Boardytale game
version: 0.0.1
author: Zdeněk Mlčoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  uuid: any
  shelf: any
  shelf_web_socket: any
  shared:
    path: ../shared
  io_utils:
    path: ../libs/io_utils
  rxdart: ^0.20.0
  stagexl: ^1.4.0+2
