name: editor_server
description: Editor server for Boardytale maps
version: 0.0.1
author: Zdeněk Mlčoch <mlcoch.zdenek@gmail.com>

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  uuid: any
  rxdart: ^0.20.0
  core:
    path: ../core
  io_utils:
    path: ../libs/io_utils

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
