name: user_server
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  uuid: any
  shelf: any
  shared:
    path: ../shared
  io_utils:
    path: ../libs/io_utils

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
