name: user_server
description: User and heroes component of Boardytale application
version: 0.0.1
author: Boardytale team - see Git log form more information

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  aqueduct: ^3.0.0
  uuid: any
  shelf: any
  core:
    path: ../core
  io_utils:
    path: ../libs/io_utils

dev_dependencies:
  test: ^1.0.0
  aqueduct_test: ^1.0.0
