name: shared
description: Multiplayre webgame on hexagonal fields common library

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  typescript_reporter:
    path: '../libs/typescript_reporter'
  utils:
    path: '../libs/utils'
  json_annotation: any

dev_dependencies:
  build_runner: any
  test: any
  json_serializable: any
  typescript_generator:
    path: ../typescript_generator/


