name: boardytale_client
description: boardytale_client
version: 0.0.1
environment:
  sdk: '>=1.19.0 <2.0.0'
dependencies:
  utils:
    path: '../utils'
  io_utils:
    path: '../io_utils'
  pub_serve_rewrites: any
