name: generated
description: A project used to demo the Todo Reporter
version: 1.0.0+1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  generate_typescript:
    path: ../libs/generate_typescript

dev_dependencies:
  build_runner: 1.0.0
  json_serializable: any
  typescript_generator:
    path: ../typescript_generator/
