name: game_client
description: Tour of Heroes
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.1
  stagexl: ^1.4.0+2
  js: any
  rxdart: ^0.20.0
  fff: any
  ng2_g_signin:
    git: https://github.com/Boardytale/ng2_g_signin
  core:
    path: ../core

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3
  build_web_compilers: ^0.4.4
  test: ^1.5.1
  sass: ^1.15.2
  io_utils:
    path: ../libs/io_utils
